version: "3.3"

services:

  database:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    env_file:
      - '../.env'
    networks:
      - canary-net
    ports:
      - "3306:3306"
    volumes:
      - 'canary:/var/lib/mysql'
      - ./schema.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "healthcheck.sh"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3

  server:
    container_name: server
    image: ghcr.io/tibia-oce/canary:0.2.0
    restart: unless-stopped
    env_file:
      - '../.env'
    networks:
      - canary-net
    depends_on:
      - database

  login:
    container_name: login
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    networks:
      - canary-net
    depends_on:
      - database
    ports:
      - "80:80"
      - "8080:8080"
      - "9090:9090"
    env_file:
      - '../.env'

  myaac:
    container_name: myaac
    image: ghcr.io/tibia-oce/myaac:0.8.19
    ports:
      - 8001:80
    restart: unless-stopped
    env_file:
      - '../.env'
    networks:
      - canary-net
    depends_on:
      - database

volumes:
  canary:

networks:
  canary-net:
    driver: bridge
